allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  prisma: set this to true or false
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.112.4'
  - '@supabase/functions-js@2.112.4'
  - '@supabase/postgrest-js@2.112.4'
  - '@supabase/realtime-js@2.112.4'
  - '@supabase/storage-js@2.112.4'
  - '@supabase/supabase-js@2.112.4'
